### ISSUE TITLE
Can we avoid blocking the WebVR render thread?

### ISSUE THREAD

**Issue by asajeffrey** [servo/rust-webvr#60]
Currently, `sync_poses` is a blocking function, which blocks the WebVR render thread until the next animation frame. This means the render thread can't perform other useful work while waiting for the next animation frame. In Servo, the WebVR render thread is the same as the WebGL thread, so the WebGL thread is blocked, leading to issues such as https://github.com/servo/servo/issues/22914, where webrender is blocked waiting on the WebGL thread.

**Comment by asajeffrey** [comment]
A potential fix: https://github.com/asajeffrey/rust-webvr/commit/1bfc1e7c6ffaeb8a8edc43a211cdf9205e5024bf

**Comment by MortimerGoro** [comment]
We can do that separation right once we get https://github.com/servo/rust-offscreen-rendering-context/issues/133 implemented. That task is blocking other many tasks (e.g. Servo WebVR in FxR). cc @jdm is already anyone working on it or is there any plan to start the work?

Another solution may be to create another GL shared context but not sure if it's worth the effort because is going to be throw away code when SurfaceTextures are ready.

**Comment by asajeffrey** [comment]
The fix I implemented is for the frame data to return a future, and to have the script thread rather than the GL thread block on it.

**Comment by asajeffrey** [comment]
Fixed by #62
